version: '3.8'

services:
  proxy:
    image: busapp-proxy
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    ports:
      - "80:80"
    networks:
      - red-overlay
    depends_on:
      - user-auth
      - bus-reservation
      - payment-gateway
      - route-scheduler

  user-auth:
    image: busapp-user-auth
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == wkr"
    networks:
      - red-overlay

  bus-reservation:
    image: busapp-bus-reservation
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == wkr"
    networks:
      - red-overlay

  payment-gateway:
    image: busapp-payment-gateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == wkr"
    networks:
      - red-overlay

  route-scheduler:
    image: busapp-route-scheduler
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname == wkr"
    networks:
      - red-overlay

networks:
  red-overlay:
    driver: overlay
